
INSERT INTO language
VALUES
(uuidv7(), CURRENT_TIMESTAMP, 'Afar', 'aa', 'aar', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Abkhazian', 'ab', 'abk', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Afrikaans', 'af', 'afr', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Akan', 'ak', 'aka', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Amharic', 'am', 'amh', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Aragonese', 'an', 'arg', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Arabic', 'ar', 'ara', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Assamese', 'as', 'asm', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Avaric', 'av', 'ava', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Avestan', 'ae', 'ave', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Aymara', 'ay', 'aym', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Azerbaijani', 'az', 'aze', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Bashkir', 'ba', 'bak', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Belarusian', 'be', 'bel', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Bulgarian', 'bg', 'bul', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Bihari', 'bh', 'bih', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Bislama', 'bi', 'bis', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Bambara', 'bm', 'bam', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Bengali', 'bn', 'ben', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Breton', 'br', 'bre', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Bosnian', 'bs', 'bos', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Catalan', 'ca', 'cat', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Chechen', 'ce', 'che', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Chamorro', 'ch', 'cha', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Corsican', 'co', 'cos', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Cree', 'cr', 'cre', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Czech', 'cs', 'ces', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Church Slavic', 'cu', 'chu', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Chuvash', 'cv', 'chv', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Welsh', 'cy', 'cym', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Danish', 'da', 'dan', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'German', 'de', 'deu', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Swiss German', 'de', 'gsw', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Divehi', 'dv', 'div', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Dzongkha', 'dz', 'dzo', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Ewe', 'ee', 'ewe', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Greek', 'el', 'ell', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'English', 'en', 'eng', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Esperanto', 'eo', 'epo', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Spanish', 'es', 'spa', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Estonian', 'et', 'est', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Basque', 'eu', 'eus', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Persian', 'fa', 'fas', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Fulah', 'ff', 'ful', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Finnish', 'fi', 'fin', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Fijian', 'fj', 'fij', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Faroese', 'fo', 'fao', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'French', 'fr', 'fra', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Western Frisian', 'fy', 'fry', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Irish', 'ga', 'gle', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Gaelic (Scottish)', 'gd', 'gla', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Galician', 'gl', 'glg', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Guarani', 'gn', 'grn', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Gujarati', 'gu', 'guj', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Manx', 'gv', 'glv', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Hebrew', 'he', 'heb', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Hindi', 'hi', 'hin', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Hiri Motu', 'ho', 'hmo', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Hungarian', 'hu', 'hun', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Armenian', 'hy', 'hye', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Herero', 'hz', 'her', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Interlingua', 'ia', 'ina', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Indonesian', 'id', 'ind', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Interlingue', 'ie', 'ile', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Igbo', 'ig', 'ibo', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Sichuan Yi', 'ii', 'iii', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Ido', 'io', 'ido', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Icelandic', 'is', 'isl', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Italian', 'it', 'ita', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Inuktitut', 'iu', 'iku', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Japanese', 'ja', 'jpn', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Javanese', 'jv', 'jav', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Georgian', 'ka', 'kat', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Kikuyu', 'ki', 'kik', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Kwanyama', 'kj', 'kua', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Kazakh', 'kk', 'kaz', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Kashmiri', 'ks', 'kas', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Kannada', 'kn', 'kan', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Kashubian', NULL, 'csb', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Komi', 'kv', 'kom', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Kongo', 'kg', 'kon', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Korean', 'ko', 'kor', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Kurdish', 'ku', 'kur', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Latin', 'la', 'lat', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Luxembourgish', 'lb', 'ltz', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Ganda', 'lg', 'lug', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Limburgish', 'li', 'lim', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Lingala', 'ln', 'lin', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Lao', 'lo', 'lao', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Lithuanian', 'lt', 'lit', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Luba-Katanga', NULL, 'lub', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Latvian', 'lv', 'lav', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Malagasy', 'mg', 'mlg', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Marshallese', 'mh', 'mah', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Maori', 'mi', 'mri', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Mongolian', 'mn', 'mon', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Marathi', 'mr', 'mar', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Malay', 'ms', 'msa', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Burmese', 'my', 'mya', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Nauru', 'na', 'nau', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Bokmål, Norwegian', 'nb', 'nob', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Ndonga', 'ng', 'ndo', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Nepali', 'ne', 'nep', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Norwegian Nynorsk', 'nn', 'nno', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Ndebele, North', 'nd', 'nde', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Ndebele, South', 'nr', 'nbl', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Chichewa', 'ny', 'nya', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Occitan', 'oc', 'oci', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Ojibwa', 'oj', 'oji', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Oromo', 'om', 'orm', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Oriya', 'or', 'ori', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Ossetian', 'os', 'oss', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Panjabi', 'pa', 'pan', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Pali', NULL, 'pli', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Polish', 'pl', 'pol', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Pashto', 'ps', 'pus', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Portuguese', 'pt', 'por', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Quechua', 'qu', 'que', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Romansh', 'rm', 'roh', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Romanian', 'ro', 'ron', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Russian', 'ru', 'rus', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Kinyarwanda', 'rw', 'kin', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Sanskrit', 'sa', 'san', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Sardinian', 'sc', 'srd', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Sindhi', 'sd', 'snd', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Northern Sami', 'se', 'sme', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Sango', 'sg', 'sag', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Sinhala', 'si', 'sin', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Slovak', 'sk', 'slk', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Slovenian', 'sl', 'slv', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Samoan', 'sm', 'smo', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Shona', 'sn', 'sna', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Somali', 'so', 'som', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Albanian', 'sq', 'sqi', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Serbian', 'sr', 'srp', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Swati', 'ss', 'ssw', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Sotho, Southern', 'st', 'sot', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Sundanese', 'su', 'sun', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Swedish', 'sv', 'swe', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Swahili', 'sw', 'swa', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Tamil', 'ta', 'tam', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Telugu', 'te', 'tel', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Tajik', 'tg', 'tgk', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Thai', 'th', 'tha', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Tigrinya', 'ti', 'tir', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Tibetan', 'bo', 'bod', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Turkmen', 'tk', 'tuk', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Tagalog', 'tl', 'tgl', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Tswana', 'tn', 'tsn', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Tonga (Tonga Islands)', 'to', 'ton', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Turkish', 'tr', 'tur', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Tsonga', 'ts', 'tso', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Tatar', 'tt', 'tat', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Twi', 'tw', 'twi', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Tahitian', 'ty', 'tah', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Uighur', 'ug', 'uig', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Ukrainian', 'uk', 'ukr', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Urdu', 'ur', 'urd', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Uzbek', 'uz', 'uzb', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Venda', 've', 'ven', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Vietnamese', 'vi', 'vie', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Volapük', 'vo', 'vol', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Walloon', 'wa', 'wln', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Wolof', 'wo', 'wol', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Xhosa', 'xh', 'xho', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Yiddish', 'yi', 'yid', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Yoruba', 'yo', 'yor', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Zhuang', 'za', 'zha', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Zulu', 'zu', 'zul', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Kanuri', 'kr', 'kau', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Hausa', 'ha', 'hau', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Inupiaq', 'ik', 'ipk', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Macedonian', 'mk', 'mkd', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Malayalam', 'ml', 'mal', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Maltese', 'mt', 'mlt', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Dutch', 'nl', 'nld', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Hmong', NULL, 'hmn', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Balochi', NULL, 'bal', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Maithili', NULL, 'mai', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Chhattisgarhi', NULL, 'hne', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Mandarin Chinese', NULL, 'cmn', NULL),
(uuidv7(), CURRENT_TIMESTAMP, 'Chinese', 'zh', 'zho', NULL);

UPDATE language
SET parent_id = 
(
    SELECT lan.id FROM language lan WHERE lan.iso639_3 = 'deu'
)
WHERE iso639_3 = 'gsw';

UPDATE language
SET parent_id =
(
    SELECT lan.id FROM language lan WHERE lan.iso639_3 = 'zho'
)
WHERE iso639_3 = 'cmn';