
INSERT INTO language
(
    name,
    iso639_1,
    iso639_3,
    ietf_bcp_47,
    is_dialect,
    is_regional_standard
)
VALUES
('Afar', 'aa', 'aar', 'aa', FALSE, FALSE),
('Abkhazian', 'ab', 'abk', 'ab', FALSE, FALSE),
('Afrikaans', 'af', 'afr', 'af', FALSE, FALSE),
('Akan', 'ak', 'aka', 'ak', FALSE, FALSE),
('Amharic', 'am', 'amh', 'am', FALSE, FALSE),
('Aragonese', 'an', 'arg', 'an', FALSE, FALSE),
('Arabic', 'ar', 'ara', 'ar', FALSE, FALSE),
('Assamese', 'as', 'asm', 'as', FALSE, FALSE),
('Avaric', 'av', 'ava', 'av', FALSE, FALSE),
('Avestan', 'ae', 'ave', 'ae', FALSE, FALSE),
('Aymara', 'ay', 'aym', '', FALSE, FALSE),
('Azerbaijani', 'az', 'aze', '', FALSE, FALSE),
('Bashkir', 'ba', 'bak', '', FALSE, FALSE),
('Belarusian', 'be', 'bel', '', FALSE, FALSE),
('Bulgarian', 'bg', 'bul', '', FALSE, FALSE),
('Bihari', 'bh', 'bih', '', FALSE, FALSE),
('Bislama', 'bi', 'bis', '', FALSE, FALSE),
('Bambara', 'bm', 'bam', '', FALSE, FALSE),
('Bengali', 'bn', 'ben', '', FALSE, FALSE),
('Breton', 'br', 'bre', '', FALSE, FALSE),
('Bosnian', 'bs', 'bos', '', FALSE, FALSE),
('Catalan', 'ca', 'cat', '', FALSE, FALSE),
('Chechen', 'ce', 'che', '', FALSE, FALSE),
('Chamorro', 'ch', 'cha', '', FALSE, FALSE),
('Corsican', 'co', 'cos', '', FALSE, FALSE),
('Cree', 'cr', 'cre', '', FALSE, FALSE),
('Czech', 'cs', 'ces', '', FALSE, FALSE),
('Church Slavic', 'cu', 'chu', '', FALSE, FALSE),
('Chuvash', 'cv', 'chv', '', FALSE, FALSE),
('Welsh', 'cy', 'cym', '', FALSE, FALSE),
('Danish', 'da', 'dan', '', FALSE, FALSE),
('German', 'de', 'deu', '', FALSE, FALSE),
('Swiss German', 'de', 'gsw', 'gsw-CH', TRUE, FALSE),
('Swiss Standard German', 'de', 'deu', 'de-CH', FALSE, TRUE),
('Austrian German', 'de', 'deu', 'de-AT', FALSE, TRUE),
('Divehi', 'dv', 'div', '', FALSE, FALSE),
('Dzongkha', 'dz', 'dzo', '', FALSE, FALSE),
('Ewe', 'ee', 'ewe', '', FALSE, FALSE),
('Greek', 'el', 'ell', '', FALSE, FALSE),
('English', 'en', 'eng', '', FALSE, FALSE),
('Esperanto', 'eo', 'epo', '', FALSE, FALSE),
('Spanish', 'es', 'spa', '', FALSE, FALSE),
('Estonian', 'et', 'est', '', FALSE, FALSE),
('Basque', 'eu', 'eus', '', FALSE, FALSE),
('Persian', 'fa', 'fas', '', FALSE, FALSE),
('Fulah', 'ff', 'ful', '', FALSE, FALSE),
('Finnish', 'fi', 'fin', '', FALSE, FALSE),
('Fijian', 'fj', 'fij', '', FALSE, FALSE),
('Faroese', 'fo', 'fao', '', FALSE, FALSE),
('French', 'fr', 'fra', '', FALSE, FALSE),
('Western Frisian', 'fy', 'fry', '', FALSE, FALSE),
('Irish', 'ga', 'gle', '', FALSE, FALSE),
('Gaelic (Scottish)', 'gd', 'gla', '', FALSE, FALSE),
('Galician', 'gl', 'glg', '', FALSE, FALSE),
('Guarani', 'gn', 'grn', '', FALSE, FALSE),
('Gujarati', 'gu', 'guj', '', FALSE, FALSE),
('Manx', 'gv', 'glv', '', FALSE, FALSE),
('Hebrew', 'he', 'heb', '', FALSE, FALSE),
('Hindi', 'hi', 'hin', '', FALSE, FALSE),
('Hiri Motu', 'ho', 'hmo', '', FALSE, FALSE),
('Hungarian', 'hu', 'hun', '', FALSE, FALSE),
('Armenian', 'hy', 'hye', '', FALSE, FALSE),
('Herero', 'hz', 'her', '', FALSE, FALSE),
('Interlingua', 'ia', 'ina', '', FALSE, FALSE),
('Indonesian', 'id', 'ind', '', FALSE, FALSE),
('Interlingue', 'ie', 'ile', '', FALSE, FALSE),
('Igbo', 'ig', 'ibo', '', FALSE, FALSE),
('Sichuan Yi', 'ii', 'iii', '', FALSE, FALSE),
('Ido', 'io', 'ido', '', FALSE, FALSE),
('Icelandic', 'is', 'isl', '', FALSE, FALSE),
('Italian', 'it', 'ita', '', FALSE, FALSE),
('Inuktitut', 'iu', 'iku', '', FALSE, FALSE),
('Japanese', 'ja', 'jpn', '', FALSE, FALSE),
('Javanese', 'jv', 'jav', '', FALSE, FALSE),
('Georgian', 'ka', 'kat', '', FALSE, FALSE),
('Kikuyu', 'ki', 'kik', '', FALSE, FALSE),
('Kwanyama', 'kj', 'kua', '', FALSE, FALSE),
('Kazakh', 'kk', 'kaz', '', FALSE, FALSE),
('Kashmiri', 'ks', 'kas', '', FALSE, FALSE),
('Kannada', 'kn', 'kan', '', FALSE, FALSE),
('Kashubian', 'csb', '', FALSE, FALSE),
('Komi', 'kv', 'kom', '', FALSE, FALSE),
('Kongo', 'kg', 'kon', '', FALSE, FALSE),
('Korean', 'ko', 'kor', '', FALSE, FALSE),
('Kurdish', 'ku', 'kur', '', FALSE, FALSE),
('Latin', 'la', 'lat', '', FALSE, FALSE),
('Luxembourgish', 'lb', 'ltz', '', FALSE, FALSE),
('Ganda', 'lg', 'lug', '', FALSE, FALSE),
('Limburgish', 'li', 'lim', '', FALSE, FALSE),
('Lingala', 'ln', 'lin', '', FALSE, FALSE),
('Lao', 'lo', 'lao', '', FALSE, FALSE),
('Lithuanian', 'lt', 'lit', '', FALSE, FALSE),
('Luba-Katanga', 'lub', '', FALSE, FALSE),
('Latvian', 'lv', 'lav', '', FALSE, FALSE),
('Malagasy', 'mg', 'mlg', '', FALSE, FALSE),
('Marshallese', 'mh', 'mah', '', FALSE, FALSE),
('Maori', 'mi', 'mri', '', FALSE, FALSE),
('Mongolian', 'mn', 'mon', '', FALSE, FALSE),
('Marathi', 'mr', 'mar', '', FALSE, FALSE),
('Malay', 'ms', 'msa', '', FALSE, FALSE),
('Burmese', 'my', 'mya', '', FALSE, FALSE),
('Nauru', 'na', 'nau', '', FALSE, FALSE),
('Bokmål, Norwegian', 'nb', 'nob', '', FALSE, FALSE),
('Ndonga', 'ng', 'ndo', '', FALSE, FALSE),
('Nepali', 'ne', 'nep', '', FALSE, FALSE),
('Norwegian Nynorsk', 'nn', 'nno', '', FALSE, FALSE),
('Ndebele, North', 'nd', 'nde', '', FALSE, FALSE),
('Ndebele, South', 'nr', 'nbl', '', FALSE, FALSE),
('Chichewa', 'ny', 'nya', '', FALSE, FALSE),
('Occitan', 'oc', 'oci', '', FALSE, FALSE),
('Ojibwa', 'oj', 'oji', '', FALSE, FALSE),
('Oromo', 'om', 'orm', '', FALSE, FALSE),
('Oriya', 'or', 'ori', '', FALSE, FALSE),
('Ossetian', 'os', 'oss', '', FALSE, FALSE),
('Panjabi', 'pa', 'pan', '', FALSE, FALSE),
('Pali', 'pli', '', FALSE, FALSE),
('Polish', 'pl', 'pol', '', FALSE, FALSE),
('Pashto', 'ps', 'pus', '', FALSE, FALSE),
('Portuguese', 'pt', 'por', '', FALSE, FALSE),
('Quechua', 'qu', 'que', '', FALSE, FALSE),
('Romansh', 'rm', 'roh', '', FALSE, FALSE),
('Romanian', 'ro', 'ron', '', FALSE, FALSE),
('Russian', 'ru', 'rus', '', FALSE, FALSE),
('Kinyarwanda', 'rw', 'kin', '', FALSE, FALSE),
('Sanskrit', 'sa', 'san', '', FALSE, FALSE),
('Sardinian', 'sc', 'srd', '', FALSE, FALSE),
('Sindhi', 'sd', 'snd', '', FALSE, FALSE),
('Northern Sami', 'se', 'sme', '', FALSE, FALSE),
('Sango', 'sg', 'sag', '', FALSE, FALSE),
('Sinhala', 'si', 'sin', '', FALSE, FALSE),
('Slovak', 'sk', 'slk', '', FALSE, FALSE),
('Slovenian', 'sl', 'slv', '', FALSE, FALSE),
('Samoan', 'sm', 'smo', '', FALSE, FALSE),
('Shona', 'sn', 'sna', '', FALSE, FALSE),
('Somali', 'so', 'som', '', FALSE, FALSE),
('Albanian', 'sq', 'sqi', '', FALSE, FALSE),
('Serbian', 'sr', 'srp', '', FALSE, FALSE),
('Swati', 'ss', 'ssw', '', FALSE, FALSE),
('Sotho, Southern', 'st', 'sot', '', FALSE, FALSE),
('Sundanese', 'su', 'sun', '', FALSE, FALSE),
('Swedish', 'sv', 'swe', '', FALSE, FALSE),
('Swahili', 'sw', 'swa', '', FALSE, FALSE),
('Tamil', 'ta', 'tam', '', FALSE, FALSE),
('Telugu', 'te', 'tel', '', FALSE, FALSE),
('Tajik', 'tg', 'tgk', '', FALSE, FALSE),
('Thai', 'th', 'tha', '', FALSE, FALSE),
('Tigrinya', 'ti', 'tir', '', FALSE, FALSE),
('Tibetan', 'bo', 'bod', '', FALSE, FALSE),
('Turkmen', 'tk', 'tuk', '', FALSE, FALSE),
('Tagalog', 'tl', 'tgl', '', FALSE, FALSE),
('Tswana', 'tn', 'tsn', '', FALSE, FALSE),
('Tonga (Tonga Islands)', 'to', 'ton', '', FALSE, FALSE),
('Turkish', 'tr', 'tur', '', FALSE, FALSE),
('Tsonga', 'ts', 'tso', '', FALSE, FALSE),
('Tatar', 'tt', 'tat', '', FALSE, FALSE),
('Twi', 'tw', 'twi', '', FALSE, FALSE),
('Tahitian', 'ty', 'tah', '', FALSE, FALSE),
('Uighur', 'ug', 'uig', '', FALSE, FALSE),
('Ukrainian', 'uk', 'ukr', '', FALSE, FALSE),
('Urdu', 'ur', 'urd', '', FALSE, FALSE),
('Uzbek', 'uz', 'uzb', '', FALSE, FALSE),
('Venda', 've', 'ven', '', FALSE, FALSE),
('Vietnamese', 'vi', 'vie', '', FALSE, FALSE),
('Volapük', 'vo', 'vol', '', FALSE, FALSE),
('Walloon', 'wa', 'wln', '', FALSE, FALSE),
('Wolof', 'wo', 'wol', '', FALSE, FALSE),
('Xhosa', 'xh', 'xho', '', FALSE, FALSE),
('Yiddish', 'yi', 'yid', '', FALSE, FALSE),
('Yoruba', 'yo', 'yor', '', FALSE, FALSE),
('Zhuang', 'za', 'zha', '', FALSE, FALSE),
('Zulu', 'zu', 'zul', '', FALSE, FALSE),
('Kanuri', 'kr', 'kau', '', FALSE, FALSE),
('Hausa', 'ha', 'hau', '', FALSE, FALSE),
('Inupiaq', 'ik', 'ipk', '', FALSE, FALSE),
('Macedonian', 'mk', 'mkd', '', FALSE, FALSE),
('Malayalam', 'ml', 'mal', '', FALSE, FALSE),
('Maltese', 'mt', 'mlt', '', FALSE, FALSE),
('Dutch', 'nl', 'nld', '', FALSE, FALSE),
('Hmong', 'hmn', '', FALSE, FALSE),
('Balochi', 'bal', '', FALSE, FALSE),
('Maithili', 'mai', '', FALSE, FALSE),
('Chhattisgarhi', 'hne', '', FALSE, FALSE),
('Mandarin Chinese', 'cmn', '', FALSE, FALSE),
('Chinese', 'zh', 'zho', '', FALSE, FALSE);

UPDATE language
SET parent_id = 
(
    SELECT lan.id FROM language lan WHERE lan.iso639_3 = 'deu'
)
WHERE iso639_3 = 'gsw';

UPDATE language
SET parent_id = 
(
    SELECT lan.id FROM language lan WHERE lan.iso639_3 = 'deu'
)
WHERE ietf_bcp_47 = 'de-AT';

UPDATE language
SET parent_id =
(
    SELECT lan.id FROM language lan WHERE lan.iso639_3 = 'zho'
)
WHERE iso639_3 = 'cmn';