
INSERT INTO language
(
    name,
    iso639_1,
    iso639_3,
    parent_id
)
VALUES
('Afar', 'aa', 'aar', NULL),
('Abkhazian', 'ab', 'abk', NULL),
('Afrikaans', 'af', 'afr', NULL),
('Akan', 'ak', 'aka', NULL),
('Amharic', 'am', 'amh', NULL),
('Aragonese', 'an', 'arg', NULL),
('Arabic', 'ar', 'ara', NULL),
('Assamese', 'as', 'asm', NULL),
('Avaric', 'av', 'ava', NULL),
('Avestan', 'ae', 'ave', NULL),
('Aymara', 'ay', 'aym', NULL),
('Azerbaijani', 'az', 'aze', NULL),
('Bashkir', 'ba', 'bak', NULL),
('Belarusian', 'be', 'bel', NULL),
('Bulgarian', 'bg', 'bul', NULL),
('Bihari', 'bh', 'bih', NULL),
('Bislama', 'bi', 'bis', NULL),
('Bambara', 'bm', 'bam', NULL),
('Bengali', 'bn', 'ben', NULL),
('Breton', 'br', 'bre', NULL),
('Bosnian', 'bs', 'bos', NULL),
('Catalan', 'ca', 'cat', NULL),
('Chechen', 'ce', 'che', NULL),
('Chamorro', 'ch', 'cha', NULL),
('Corsican', 'co', 'cos', NULL),
('Cree', 'cr', 'cre', NULL),
('Czech', 'cs', 'ces', NULL),
('Church Slavic', 'cu', 'chu', NULL),
('Chuvash', 'cv', 'chv', NULL),
('Welsh', 'cy', 'cym', NULL),
('Danish', 'da', 'dan', NULL),
('German', 'de', 'deu', NULL),
('Swiss German', 'de', 'gsw', NULL),
('Divehi', 'dv', 'div', NULL),
('Dzongkha', 'dz', 'dzo', NULL),
('Ewe', 'ee', 'ewe', NULL),
('Greek', 'el', 'ell', NULL),
('English', 'en', 'eng', NULL),
('Esperanto', 'eo', 'epo', NULL),
('Spanish', 'es', 'spa', NULL),
('Estonian', 'et', 'est', NULL),
('Basque', 'eu', 'eus', NULL),
('Persian', 'fa', 'fas', NULL),
('Fulah', 'ff', 'ful', NULL),
('Finnish', 'fi', 'fin', NULL),
('Fijian', 'fj', 'fij', NULL),
('Faroese', 'fo', 'fao', NULL),
('French', 'fr', 'fra', NULL),
('Western Frisian', 'fy', 'fry', NULL),
('Irish', 'ga', 'gle', NULL),
('Gaelic (Scottish)', 'gd', 'gla', NULL),
('Galician', 'gl', 'glg', NULL),
('Guarani', 'gn', 'grn', NULL),
('Gujarati', 'gu', 'guj', NULL),
('Manx', 'gv', 'glv', NULL),
('Hebrew', 'he', 'heb', NULL),
('Hindi', 'hi', 'hin', NULL),
('Hiri Motu', 'ho', 'hmo', NULL),
('Hungarian', 'hu', 'hun', NULL),
('Armenian', 'hy', 'hye', NULL),
('Herero', 'hz', 'her', NULL),
('Interlingua', 'ia', 'ina', NULL),
('Indonesian', 'id', 'ind', NULL),
('Interlingue', 'ie', 'ile', NULL),
('Igbo', 'ig', 'ibo', NULL),
('Sichuan Yi', 'ii', 'iii', NULL),
('Ido', 'io', 'ido', NULL),
('Icelandic', 'is', 'isl', NULL),
('Italian', 'it', 'ita', NULL),
('Inuktitut', 'iu', 'iku', NULL),
('Japanese', 'ja', 'jpn', NULL),
('Javanese', 'jv', 'jav', NULL),
('Georgian', 'ka', 'kat', NULL),
('Kikuyu', 'ki', 'kik', NULL),
('Kwanyama', 'kj', 'kua', NULL),
('Kazakh', 'kk', 'kaz', NULL),
('Kashmiri', 'ks', 'kas', NULL),
('Kannada', 'kn', 'kan', NULL),
('Kashubian', NULL, 'csb', NULL),
('Komi', 'kv', 'kom', NULL),
('Kongo', 'kg', 'kon', NULL),
('Korean', 'ko', 'kor', NULL),
('Kurdish', 'ku', 'kur', NULL),
('Latin', 'la', 'lat', NULL),
('Luxembourgish', 'lb', 'ltz', NULL),
('Ganda', 'lg', 'lug', NULL),
('Limburgish', 'li', 'lim', NULL),
('Lingala', 'ln', 'lin', NULL),
('Lao', 'lo', 'lao', NULL),
('Lithuanian', 'lt', 'lit', NULL),
('Luba-Katanga', NULL, 'lub', NULL),
('Latvian', 'lv', 'lav', NULL),
('Malagasy', 'mg', 'mlg', NULL),
('Marshallese', 'mh', 'mah', NULL),
('Maori', 'mi', 'mri', NULL),
('Mongolian', 'mn', 'mon', NULL),
('Marathi', 'mr', 'mar', NULL),
('Malay', 'ms', 'msa', NULL),
('Burmese', 'my', 'mya', NULL),
('Nauru', 'na', 'nau', NULL),
('Bokmål, Norwegian', 'nb', 'nob', NULL),
('Ndonga', 'ng', 'ndo', NULL),
('Nepali', 'ne', 'nep', NULL),
('Norwegian Nynorsk', 'nn', 'nno', NULL),
('Ndebele, North', 'nd', 'nde', NULL),
('Ndebele, South', 'nr', 'nbl', NULL),
('Chichewa', 'ny', 'nya', NULL),
('Occitan', 'oc', 'oci', NULL),
('Ojibwa', 'oj', 'oji', NULL),
('Oromo', 'om', 'orm', NULL),
('Oriya', 'or', 'ori', NULL),
('Ossetian', 'os', 'oss', NULL),
('Panjabi', 'pa', 'pan', NULL),
('Pali', NULL, 'pli', NULL),
('Polish', 'pl', 'pol', NULL),
('Pashto', 'ps', 'pus', NULL),
('Portuguese', 'pt', 'por', NULL),
('Quechua', 'qu', 'que', NULL),
('Romansh', 'rm', 'roh', NULL),
('Romanian', 'ro', 'ron', NULL),
('Russian', 'ru', 'rus', NULL),
('Kinyarwanda', 'rw', 'kin', NULL),
('Sanskrit', 'sa', 'san', NULL),
('Sardinian', 'sc', 'srd', NULL),
('Sindhi', 'sd', 'snd', NULL),
('Northern Sami', 'se', 'sme', NULL),
('Sango', 'sg', 'sag', NULL),
('Sinhala', 'si', 'sin', NULL),
('Slovak', 'sk', 'slk', NULL),
('Slovenian', 'sl', 'slv', NULL),
('Samoan', 'sm', 'smo', NULL),
('Shona', 'sn', 'sna', NULL),
('Somali', 'so', 'som', NULL),
('Albanian', 'sq', 'sqi', NULL),
('Serbian', 'sr', 'srp', NULL),
('Swati', 'ss', 'ssw', NULL),
('Sotho, Southern', 'st', 'sot', NULL),
('Sundanese', 'su', 'sun', NULL),
('Swedish', 'sv', 'swe', NULL),
('Swahili', 'sw', 'swa', NULL),
('Tamil', 'ta', 'tam', NULL),
('Telugu', 'te', 'tel', NULL),
('Tajik', 'tg', 'tgk', NULL),
('Thai', 'th', 'tha', NULL),
('Tigrinya', 'ti', 'tir', NULL),
('Tibetan', 'bo', 'bod', NULL),
('Turkmen', 'tk', 'tuk', NULL),
('Tagalog', 'tl', 'tgl', NULL),
('Tswana', 'tn', 'tsn', NULL),
('Tonga (Tonga Islands)', 'to', 'ton', NULL),
('Turkish', 'tr', 'tur', NULL),
('Tsonga', 'ts', 'tso', NULL),
('Tatar', 'tt', 'tat', NULL),
('Twi', 'tw', 'twi', NULL),
('Tahitian', 'ty', 'tah', NULL),
('Uighur', 'ug', 'uig', NULL),
('Ukrainian', 'uk', 'ukr', NULL),
('Urdu', 'ur', 'urd', NULL),
('Uzbek', 'uz', 'uzb', NULL),
('Venda', 've', 'ven', NULL),
('Vietnamese', 'vi', 'vie', NULL),
('Volapük', 'vo', 'vol', NULL),
('Walloon', 'wa', 'wln', NULL),
('Wolof', 'wo', 'wol', NULL),
('Xhosa', 'xh', 'xho', NULL),
('Yiddish', 'yi', 'yid', NULL),
('Yoruba', 'yo', 'yor', NULL),
('Zhuang', 'za', 'zha', NULL),
('Zulu', 'zu', 'zul', NULL),
('Kanuri', 'kr', 'kau', NULL),
('Hausa', 'ha', 'hau', NULL),
('Inupiaq', 'ik', 'ipk', NULL),
('Macedonian', 'mk', 'mkd', NULL),
('Malayalam', 'ml', 'mal', NULL),
('Maltese', 'mt', 'mlt', NULL),
('Dutch', 'nl', 'nld', NULL),
('Hmong', NULL, 'hmn', NULL),
('Balochi', NULL, 'bal', NULL),
('Maithili', NULL, 'mai', NULL),
('Chhattisgarhi', NULL, 'hne', NULL),
('Mandarin Chinese', NULL, 'cmn', NULL),
('Chinese', 'zh', 'zho', NULL);

UPDATE language
SET parent_id = 
(
    SELECT lan.id FROM language lan WHERE lan.iso639_3 = 'deu'
)
WHERE iso639_3 = 'gsw';

UPDATE language
SET parent_id =
(
    SELECT lan.id FROM language lan WHERE lan.iso639_3 = 'zho'
)
WHERE iso639_3 = 'cmn';