INSERT INTO language (id, name, region, native_name) VALUES
    ('pt-BR', 'Brazilian Portuguese', 'Brazil', 'Português brasileiro'),
    ('en-US', 'American English', 'United States', 'American English'),
    ('en-GB', 'British English', 'United Kingdom', 'British English'),
    ('es-ES', 'European Spanish', 'Spain', 'Español de España'),
    ('es-MX', 'Mexican Spanish', 'Mexico', 'Español mexicano'),
    ('fr-FR', 'French', 'France', 'Français'),
    ('fr-CA', 'Canadian French', 'Canada', 'Français canadien'),
    ('de-DE', 'German', 'Germany', 'Deutsch'),
    ('it-IT', 'Italian', 'Italy', 'Italiano'),
    ('ja-JP', 'Japanese', 'Japan', '日本語'),
    ('ko-KR', 'Korean', 'South Korea', '한국어'),
    ('zh-Hans-CN', 'Mandarin Chinese (Simplified)', 'China', '简体中文'),
    ('pt-PT', 'European Portuguese', 'Portugal', 'Português europeu'),
    ('en-AU', 'Australian English', 'Australia', 'Australian English'),
    ('en-CA', 'Canadian English', 'Canada', 'Canadian English'),
    ('es-AR', 'Argentine Spanish', 'Argentina', 'Español argentino'),
    ('es-CO', 'Colombian Spanish', 'Colombia', 'Español colombiano'),
    ('de-AT', 'Austrian German', 'Austria', 'Österreichisches Deutsch'),
    ('de-CH', 'Swiss Standard German', 'Switzerland', 'Schweizer Hochdeutsch'),
    ('nl-NL', 'Dutch', 'Netherlands', 'Nederlands'),
    ('nl-BE', 'Flemish Dutch', 'Belgium', 'Vlaams'),
    ('sv-SE', 'Swedish', 'Sweden', 'Svenska'),
    ('nb-NO', 'Norwegian Bokmål', 'Norway', 'Norsk bokmål'),
    ('nn-NO', 'Norwegian Nynorsk', 'Norway', 'Norsk nynorsk'),
    ('da-DK', 'Danish', 'Denmark', 'Dansk'),
    ('fi-FI', 'Finnish', 'Finland', 'Suomi'),
    ('is-IS', 'Icelandic', 'Iceland', 'Íslenska'),
    ('fo-FO', 'Faroese', 'Faroe Islands', 'Føroyskt'),
    ('pl-PL', 'Polish', 'Poland', 'Polski'),
    ('cs-CZ', 'Czech', 'Czechia', 'Čeština'),
    ('sk-SK', 'Slovak', 'Slovakia', 'Slovenčina'),
    ('hu-HU', 'Hungarian', 'Hungary', 'Magyar'),
    ('ro-RO', 'Romanian', 'Romania', 'Română'),
    ('bg-BG', 'Bulgarian', 'Bulgaria', 'Български'),
    ('hr-HR', 'Croatian', 'Croatia', 'Hrvatski'),
    ('sr-RS', 'Serbian', 'Serbia', 'Српски'),
    ('bs-BA', 'Bosnian', 'Bosnia and Herzegovina', 'Bosanski'),
    ('sl-SI', 'Slovenian', 'Slovenia', 'Slovenščina'),
    ('mk-MK', 'Macedonian', 'North Macedonia', 'Македонски'),
    ('sq-AL', 'Albanian', 'Albania', 'Shqip'),
    ('el-GR', 'Greek', 'Greece', 'Ελληνικά'),
    ('tr-TR', 'Turkish', 'Türkiye', 'Türkçe'),
    ('ru-RU', 'Russian', 'Russia', 'Русский'),
    ('uk-UA', 'Ukrainian', 'Ukraine', 'Українська'),
    ('be-BY', 'Belarusian', 'Belarus', 'Беларуская'),
    ('lt-LT', 'Lithuanian', 'Lithuania', 'Lietuvių'),
    ('lv-LV', 'Latvian', 'Latvia', 'Latviešu'),
    ('et-EE', 'Estonian', 'Estonia', 'Eesti'),
    ('ga-IE', 'Irish', 'Ireland', 'Gaeilge'),
    ('gd-GB', 'Scottish Gaelic', 'Scotland', 'Gàidhlig'),
    ('cy-GB', 'Welsh', 'Wales', 'Cymraeg'),
    ('mt-MT', 'Maltese', 'Malta', 'Malti'),
    ('ca-ES', 'Catalan', 'Spain and Andorra', 'Català'),
    ('eu-ES', 'Basque', 'Spain and France', 'Euskara'),
    ('gl-ES', 'Galician', 'Spain', 'Galego'),
    ('oc-FR', 'Occitan', 'France', 'Occitan'),
    ('lb-LU', 'Luxembourgish', 'Luxembourg', 'Lëtzebuergesch'),
    ('hy-AM', 'Armenian', 'Armenia', 'Հայերեն'),
    ('ka-GE', 'Georgian', 'Georgia', 'ქართული'),
    ('az-AZ', 'Azerbaijani', 'Azerbaijan', 'Azərbaycan dili'),
    ('kk-KZ', 'Kazakh', 'Kazakhstan', 'Қазақ тілі'),
    ('uz-UZ', 'Uzbek', 'Uzbekistan', 'Oʻzbek tili'),
    ('ky-KG', 'Kyrgyz', 'Kyrgyzstan', 'Кыргызча'),
    ('tg-TJ', 'Tajik', 'Tajikistan', 'Тоҷикӣ'),
    ('mn-MN', 'Mongolian', 'Mongolia', 'Монгол'),
    ('zh-Hant-TW', 'Mandarin Chinese (Traditional)', 'Taiwan', '繁體中文'),
    ('yue-Hant-HK', 'Cantonese', 'Hong Kong', '廣東話'),
    ('vi-VN', 'Vietnamese', 'Vietnam', 'Tiếng Việt'),
    ('th-TH', 'Thai', 'Thailand', 'ไทย'),
    ('lo-LA', 'Lao', 'Laos', 'ລາວ'),
    ('km-KH', 'Khmer', 'Cambodia', 'ខ្មែរ'),
    ('my-MM', 'Burmese', 'Myanmar', 'မြန်မာဘာသာ'),
    ('id-ID', 'Indonesian', 'Indonesia', 'Bahasa Indonesia'),
    ('ms-MY', 'Malay', 'Malaysia', 'Bahasa Melayu'),
    ('fil-PH', 'Filipino', 'Philippines', 'Filipino'),
    ('jv-ID', 'Javanese', 'Indonesia', 'Basa Jawa'),
    ('su-ID', 'Sundanese', 'Indonesia', 'Basa Sunda'),
    ('hi-IN', 'Hindi', 'India', 'हिन्दी'),
    ('ur-PK', 'Urdu', 'Pakistan', 'اردو'),
    ('bn-BD', 'Bengali', 'Bangladesh and India', 'বাংলা'),
    ('pa-IN', 'Punjabi', 'India', 'ਪੰਜਾਬੀ'),
    ('gu-IN', 'Gujarati', 'India', 'ગુજરાતી'),
    ('mr-IN', 'Marathi', 'India', 'मराठी'),
    ('ta-IN', 'Tamil', 'India and Sri Lanka', 'தமிழ்'),
    ('te-IN', 'Telugu', 'India', 'తెలుగు'),
    ('kn-IN', 'Kannada', 'India', 'ಕನ್ನಡ'),
    ('ml-IN', 'Malayalam', 'India', 'മലയാളം'),
    ('si-LK', 'Sinhala', 'Sri Lanka', 'සිංහල'),
    ('ne-NP', 'Nepali', 'Nepal', 'नेपाली'),
    ('fa-IR', 'Persian', 'Iran', 'فارسی'),
    ('ps-AF', 'Pashto', 'Afghanistan and Pakistan', 'پښتو'),
    ('he-IL', 'Hebrew', 'Israel', 'עברית'),
    ('ar', 'Modern Standard Arabic', 'Middle East and North Africa', 'العربية الفصحى'),
    ('ar-EG', 'Egyptian Arabic', 'Egypt', 'العربية المصرية'),
    ('sw', 'Swahili', 'East Africa', 'Kiswahili'),
    ('af-ZA', 'Afrikaans', 'South Africa', 'Afrikaans'),
    ('zu-ZA', 'Zulu', 'South Africa', 'isiZulu'),
    ('xh-ZA', 'Xhosa', 'South Africa', 'isiXhosa'),
    ('am-ET', 'Amharic', 'Ethiopia', 'አማርኛ'),
    ('so-SO', 'Somali', 'Somalia', 'Soomaali');
