INSERT INTO language
(
    id,
    name,
    region,
    native_name
)
VALUES
    ('pt-BR', 'Brazilian Portuguese', 'Brazil', 'Português brasileiro'),
    ('en-US', 'American English', 'United States', 'American English'),
    ('en-GB', 'British English', 'United Kingdom', 'British English'),
    ('es-ES', 'European Spanish', 'Spain', 'Español de España'),
    ('es-MX', 'Mexican Spanish', 'Mexico', 'Español mexicano'),
    ('fr-FR', 'French', 'France', 'Français'),
    ('fr-CA', 'Canadian French', 'Canada', 'Français canadien'),
    ('de-DE', 'German', 'Germany', 'Deutsch'),
    ('it-IT', 'Italian', 'Italy', 'Italiano'),
    ('ja-JP', 'Japanese', 'Japan', '日本語'),
    ('ko-KR', 'Korean', 'South Korea', '한국어'),
    ('zh-Hans-CN', 'Mandarin Chinese (Simplified)', 'China', '简体中文'),
    ('pt-PT', 'European Portuguese', 'Portugal', 'Português europeu'),
    ('en-AU', 'Australian English', 'Australia', 'Australian English'),
    ('en-CA', 'Canadian English', 'Canada', 'Canadian English'),
    ('es-AR', 'Argentine Spanish', 'Argentina', 'Español argentino'),
    ('es-CO', 'Colombian Spanish', 'Colombia', 'Español colombiano'),
    ('de-AT', 'Austrian German', 'Austria', 'Österreichisches Deutsch'),
    ('de-CH', 'Swiss Standard German', 'Switzerland', 'Schweizer Hochdeutsch'),
    ('nl-NL', 'Dutch', 'Netherlands', 'Nederlands'),
    ('nl-BE', 'Flemish Dutch', 'Belgium', 'Vlaams'),
    ('sv-SE', 'Swedish', 'Sweden', 'Svenska'),
    ('nb-NO', 'Norwegian Bokmål', 'Norway', 'Norsk bokmål'),
    ('nn-NO', 'Norwegian Nynorsk', 'Norway', 'Norsk nynorsk'),
    ('da-DK', 'Danish', 'Denmark', 'Dansk'),
    ('fi-FI', 'Finnish', 'Finland', 'Suomi'),
    ('is-IS', 'Icelandic', 'Iceland', 'Íslenska'),
    ('fo-FO', 'Faroese', 'Faroe Islands', 'Føroyskt'),
    ('pl-PL', 'Polish', 'Poland', 'Polski'),
    ('cs-CZ', 'Czech', 'Czechia', 'Čeština'),
    ('sk-SK', 'Slovak', 'Slovakia', 'Slovenčina'),
    ('hu-HU', 'Hungarian', 'Hungary', 'Magyar'),
    ('ro-RO', 'Romanian', 'Romania', 'Română'),
    ('bg-BG', 'Bulgarian', 'Bulgaria', 'Български'),
    ('hr-HR', 'Croatian', 'Croatia', 'Hrvatski'),
    ('sr-RS', 'Serbian', 'Serbia', 'Српски'),
    ('bs-BA', 'Bosnian', 'Bosnia and Herzegovina', 'Bosanski'),
    ('sl-SI', 'Slovenian', 'Slovenia', 'Slovenščina'),
    ('mk-MK', 'Macedonian', 'North Macedonia', 'Македонски'),
    ('sq-AL', 'Albanian', 'Albania', 'Shqip'),
    ('el-GR', 'Greek', 'Greece', 'Ελληνικά'),
    ('tr-TR', 'Turkish', 'Türkiye', 'Türkçe'),
    ('ru-RU', 'Russian', 'Russia', 'Русский'),
    ('uk-UA', 'Ukrainian', 'Ukraine', 'Українська'),
    ('be-BY', 'Belarusian', 'Belarus', 'Беларуская'),
    ('lt-LT', 'Lithuanian', 'Lithuania', 'Lietuvių'),
    ('lv-LV', 'Latvian', 'Latvia', 'Latviešu'),
    ('et-EE', 'Estonian', 'Estonia', 'Eesti'),
    ('ga-IE', 'Irish', 'Ireland', 'Gaeilge'),
    ('gd-GB', 'Scottish Gaelic', 'Scotland', 'Gàidhlig'),
    ('cy-GB', 'Welsh', 'Wales', 'Cymraeg'),
    ('mt-MT', 'Maltese', 'Malta', 'Malti'),
    ('ca-ES', 'Catalan', 'Spain and Andorra', 'Català'),
    ('eu-ES', 'Basque', 'Spain and France', 'Euskara'),
    ('gl-ES', 'Galician', 'Spain', 'Galego'),
    ('oc-FR', 'Occitan', 'France', 'Occitan'),
    ('lb-LU', 'Luxembourgish', 'Luxembourg', 'Lëtzebuergesch'),
    ('hy-AM', 'Armenian', 'Armenia', 'Հայերեն'),
    ('ka-GE', 'Georgian', 'Georgia', 'ქართული'),
    ('az-AZ', 'Azerbaijani', 'Azerbaijan', 'Azərbaycan dili'),
    ('kk-KZ', 'Kazakh', 'Kazakhstan', 'Қазақ тілі'),
    ('uz-UZ', 'Uzbek', 'Uzbekistan', 'Oʻzbek tili'),
    ('ky-KG', 'Kyrgyz', 'Kyrgyzstan', 'Кыргызча'),
    ('tg-TJ', 'Tajik', 'Tajikistan', 'Тоҷикӣ'),
    ('mn-MN', 'Mongolian', 'Mongolia', 'Монгол'),
    ('zh-Hant-TW', 'Mandarin Chinese (Traditional)', 'Taiwan', '繁體中文'),
    ('yue-Hant-HK', 'Cantonese', 'Hong Kong', '廣東話'),
    ('vi-VN', 'Vietnamese', 'Vietnam', 'Tiếng Việt'),
    ('th-TH', 'Thai', 'Thailand', 'ไทย'),
    ('lo-LA', 'Lao', 'Laos', 'ລາວ'),
    ('km-KH', 'Khmer', 'Cambodia', 'ខ្មែរ'),
    ('my-MM', 'Burmese', 'Myanmar', 'မြန်မာဘာသာ'),
    ('id-ID', 'Indonesian', 'Indonesia', 'Bahasa Indonesia'),
    ('ms-MY', 'Malay', 'Malaysia', 'Bahasa Melayu'),
    ('fil-PH', 'Filipino', 'Philippines', 'Filipino'),
    ('jv-ID', 'Javanese', 'Indonesia', 'Basa Jawa'),
    ('su-ID', 'Sundanese', 'Indonesia', 'Basa Sunda'),
    ('hi-IN', 'Hindi', 'India', 'हिन्दी'),
    ('ur-PK', 'Urdu', 'Pakistan', 'اردو'),
    ('bn-BD', 'Bengali', 'Bangladesh and India', 'বাংলা'),
    ('pa-IN', 'Punjabi', 'India', 'ਪੰਜਾਬੀ'),
    ('gu-IN', 'Gujarati', 'India', 'ગુજરાતી'),
    ('mr-IN', 'Marathi', 'India', 'मराठी'),
    ('ta-IN', 'Tamil', 'India and Sri Lanka', 'தமிழ்'),
    ('te-IN', 'Telugu', 'India', 'తెలుగు'),
    ('kn-IN', 'Kannada', 'India', 'ಕನ್ನಡ'),
    ('ml-IN', 'Malayalam', 'India', 'മലയാളം'),
    ('si-LK', 'Sinhala', 'Sri Lanka', 'සිංහල'),
    ('ne-NP', 'Nepali', 'Nepal', 'नेपाली'),
    ('fa-IR', 'Persian', 'Iran', 'فارسی'),
    ('ps-AF', 'Pashto', 'Afghanistan and Pakistan', 'پښتو'),
    ('he-IL', 'Hebrew', 'Israel', 'עברית'),
    ('ar', 'Modern Standard Arabic', 'Middle East and North Africa', 'العربية الفصحى'),
    ('ar-EG', 'Egyptian Arabic', 'Egypt', 'العربية المصرية'),
    ('sw', 'Swahili', 'East Africa', 'Kiswahili'),
    ('af-ZA', 'Afrikaans', 'South Africa', 'Afrikaans'),
    ('zu-ZA', 'Zulu', 'South Africa', 'isiZulu'),
    ('xh-ZA', 'Xhosa', 'South Africa', 'isiXhosa'),
    ('am-ET', 'Amharic', 'Ethiopia', 'አማርኛ'),
    ('so-SO', 'Somali', 'Somalia', 'Soomaali'),
    ('es-CL', 'Chilean Spanish', 'Chile', 'Español (Chile)'),
    ('es-PE', 'Peruvian Spanish', 'Peru', 'Español (Peru)'),
    ('es-VE', 'Venezuelan Spanish', 'Venezuela', 'Español (Venezuela)'),
    ('es-UY', 'Uruguayan Spanish', 'Uruguay', 'Español (Uruguay)'),
    ('es-EC', 'Ecuadorian Spanish', 'Ecuador', 'Español (Ecuador)'),
    ('es-BO', 'Bolivian Spanish', 'Bolivia', 'Español (Bolivia)'),
    ('es-PY', 'Paraguayan Spanish', 'Paraguay', 'Español (Paraguay)'),
    ('es-CR', 'Costa Rican Spanish', 'Costa Rica', 'Español (Costa Rica)'),
    ('es-PA', 'Panamanian Spanish', 'Panama', 'Español (Panama)'),
    ('es-GT', 'Guatemalan Spanish', 'Guatemala', 'Español (Guatemala)'),
    ('es-HN', 'Honduran Spanish', 'Honduras', 'Español (Honduras)'),
    ('es-SV', 'Salvadoran Spanish', 'El Salvador', 'Español (El Salvador)'),
    ('es-NI', 'Nicaraguan Spanish', 'Nicaragua', 'Español (Nicaragua)'),
    ('es-CU', 'Cuban Spanish', 'Cuba', 'Español (Cuba)'),
    ('es-DO', 'Dominican Spanish', 'Dominican Republic', 'Español (Dominican Republic)'),
    ('es-PR', 'Puerto Rican Spanish', 'Puerto Rico', 'Español (Puerto Rico)'),
    ('en-NZ', 'New Zealand English', 'New Zealand', 'New Zealand English'),
    ('en-IE', 'Irish English', 'Ireland', 'Irish English'),
    ('en-ZA', 'South African English', 'South Africa', 'South African English'),
    ('en-IN', 'Indian English', 'India', 'Indian English'),
    ('en-SG', 'Singapore English', 'Singapore', 'Singapore English'),
    ('en-PH', 'Philippine English', 'Philippines', 'Philippine English'),
    ('en-NG', 'Nigerian English', 'Nigeria', 'Nigerian English'),
    ('en-KE', 'Kenyan English', 'Kenya', 'Kenyan English'),
    ('en-JM', 'Jamaican English', 'Jamaica', 'Jamaican English'),
    ('en-TT', 'Trinidadian and Tobagonian English', 'Trinidad and Tobago', 'Trinidadian and Tobagonian English'),
    ('fr-BE', 'Belgian French', 'Belgium', 'Français (Belgium)'),
    ('fr-CH', 'Swiss French', 'Switzerland', 'Français (Switzerland)'),
    ('fr-LU', 'Luxembourg French', 'Luxembourg', 'Français (Luxembourg)'),
    ('fr-SN', 'Senegalese French', 'Senegal', 'Français (Senegal)'),
    ('fr-CI', 'Ivorian French', 'Ivory Coast', 'Français (Ivory Coast)'),
    ('fr-CM', 'Cameroonian French', 'Cameroon', 'Français (Cameroon)'),
    ('fr-CD', 'Congolese French', 'Democratic Republic of the Congo', 'Français (Democratic Republic of the Congo)'),
    ('fr-HT', 'Haitian French', 'Haiti', 'Français (Haiti)'),
    ('pt-AO', 'Angolan Portuguese', 'Angola', 'Português (Angola)'),
    ('pt-MZ', 'Mozambican Portuguese', 'Mozambique', 'Português (Mozambique)'),
    ('pt-CV', 'Cape Verdean Portuguese', 'Cape Verde', 'Português (Cape Verde)'),
    ('pt-GW', 'Guinea-Bissau Portuguese', 'Guinea-Bissau', 'Português (Guinea-Bissau)'),
    ('pt-ST', 'Sao Tome and Principe Portuguese', 'Sao Tome and Principe', 'Português (Sao Tome and Principe)'),
    ('de-LU', 'Luxembourg German', 'Luxembourg', 'Deutsch (Luxembourg)'),
    ('de-LI', 'Liechtenstein German', 'Liechtenstein', 'Deutsch (Liechtenstein)'),
    ('it-CH', 'Swiss Italian', 'Switzerland', 'Italiano (Switzerland)'),
    ('nl-SR', 'Surinamese Dutch', 'Suriname', 'Nederlands (Suriname)'),
    ('ar-SA', 'Saudi Arabic', 'Saudi Arabia', 'العربية (Saudi Arabia)'),
    ('ar-MA', 'Moroccan Arabic', 'Morocco', 'العربية (Morocco)'),
    ('ar-DZ', 'Algerian Arabic', 'Algeria', 'العربية (Algeria)'),
    ('ar-TN', 'Tunisian Arabic', 'Tunisia', 'العربية (Tunisia)'),
    ('ar-LB', 'Lebanese Arabic', 'Lebanon', 'العربية (Lebanon)'),
    ('sw-KE', 'Kenyan Swahili', 'Kenya', 'Kiswahili (Kenya)'),
    ('sw-TZ', 'Tanzanian Swahili', 'Tanzania', 'Kiswahili (Tanzania)');
