INSERT INTO language_feature
(
    id,
    name,
    description,
    group_code,
    display_order
)
VALUES
    ('definite_articles', 'Definite articles', 'Grammatical markers of definite noun reference; includes words and affixes.', 'grammar', 10),
    ('indefinite_articles', 'Indefinite articles', 'Grammatical markers introducing indefinite noun reference.', 'grammar', 20),
    ('noun_gender', 'Noun gender', 'Grammatical noun classes governing agreement; excludes gendered pronouns alone and lexical male/female word pairs.', 'grammar', 30),
    ('noun_cases', 'Noun cases', 'Case inflection on common nouns; pronoun-only distinctions do not count.', 'grammar', 40),
    ('plural_formation', 'Plural formation', 'How noun number is expressed; a summary does not imply every noun follows one pattern.', 'grammar', 50),
    ('verb_conjugation', 'Verb conjugation', 'Inflection of verbs for grammatical distinctions such as person, number, tense or mood.', 'grammar', 60),
    ('grammatical_tense', 'Grammatical tense', 'Grammatical marking of time reference; lexical time expressions alone do not count.', 'grammar', 70),
    ('adjective_agreement', 'Adjective agreement', 'Adjectives change form to agree with nouns in features such as gender, number or case.', 'grammar', 80),
    ('word_order', 'Word order', 'Basic subject, verb and object order in neutral clauses; flexibility is recorded separately.', 'syntax', 90),
    ('word_order_flexibility', 'Word order flexibility', 'Permitted variation in constituent order; flexible does not mean unrestricted.', 'syntax', 100),
    ('lexical_tone', 'Lexical tone', 'Pitch contrasts distinguish lexical meanings; ordinary sentence intonation is separate.', 'phonology', 110),
    ('word_stress', 'Word stress', 'Placement of word-level stress; exceptions and variation belong in assignment notes.', 'phonology', 120);

INSERT INTO language_feature_value
(
    feature_id,
    code,
    badge_label,
    description
)
VALUES
    ('definite_articles', 'present', 'Definite articles', 'Definite articles is present within the feature definition.'),
    ('definite_articles', 'absent', 'No definite articles', 'Definite articles is absent within the feature definition.'),
    ('definite_articles', 'limited', 'Limited definite articles', 'Definite articles is restricted to a subset of relevant forms or constructions.'),
    ('indefinite_articles', 'present', 'Indefinite articles', 'Indefinite articles is present within the feature definition.'),
    ('indefinite_articles', 'absent', 'No indefinite articles', 'Indefinite articles is absent within the feature definition.'),
    ('indefinite_articles', 'limited', 'Limited indefinite articles', 'Indefinite articles is restricted to a subset of relevant forms or constructions.'),
    ('noun_cases', 'present', 'Noun cases', 'Noun cases is present within the feature definition.'),
    ('noun_cases', 'absent', 'No noun cases', 'Noun cases is absent within the feature definition.'),
    ('noun_cases', 'limited', 'Limited noun cases', 'Noun cases is restricted to a subset of relevant forms or constructions.'),
    ('verb_conjugation', 'present', 'Verb conjugation', 'Verb conjugation is present within the feature definition.'),
    ('verb_conjugation', 'absent', 'No verb conjugation', 'Verb conjugation is absent within the feature definition.'),
    ('verb_conjugation', 'limited', 'Limited verb conjugation', 'Verb conjugation is restricted to a subset of relevant forms or constructions.'),
    ('grammatical_tense', 'present', 'Grammatical tense', 'Grammatical tense is present within the feature definition.'),
    ('grammatical_tense', 'absent', 'No grammatical tense', 'Grammatical tense is absent within the feature definition.'),
    ('grammatical_tense', 'limited', 'Limited grammatical tense', 'Grammatical tense is restricted to a subset of relevant forms or constructions.'),
    ('adjective_agreement', 'present', 'Adjective agreement', 'Adjective agreement is present within the feature definition.'),
    ('adjective_agreement', 'absent', 'No adjective agreement', 'Adjective agreement is absent within the feature definition.'),
    ('adjective_agreement', 'limited', 'Limited adjective agreement', 'Adjective agreement is restricted to a subset of relevant forms or constructions.'),
    ('lexical_tone', 'present', 'Lexical tone', 'Lexical tone is present within the feature definition.'),
    ('lexical_tone', 'absent', 'No lexical tone', 'Lexical tone is absent within the feature definition.'),
    ('lexical_tone', 'limited', 'Limited lexical tone', 'Lexical tone is restricted to a subset of relevant forms or constructions.'),
    ('noun_gender', 'absent', 'No grammatical noun gender', 'No productive noun-class agreement system within this definition.'),
    ('noun_gender', 'two', 'Two noun genders', 'Two principal grammatical genders; exceptions are described in notes.'),
    ('noun_gender', 'three', 'Three noun genders', 'Three principal grammatical genders; subtypes may govern additional agreement patterns.'),
    ('noun_gender', 'multiple', 'Multiple noun genders', 'A noun-class system not adequately summarized by two or three genders.'),
    ('plural_formation', 'inflected', 'Inflected plurals', 'Plurality can be marked by changes to noun form.'),
    ('plural_formation', 'particles', 'Plural particles', 'Separate particles can mark noun plurality.'),
    ('plural_formation', 'mixed', 'Mixed plural marking', 'Several number-marking strategies coexist.'),
    ('plural_formation', 'unmarked', 'No regular noun plural marking', 'Nouns have no regular productive plural marking; context and quantifiers may express number.'),
    ('word_order', 'svo', 'Subject-verb-object', 'Neutral transitive clauses commonly order subject before verb before object.'),
    ('word_order', 'sov', 'Subject-object-verb', 'Neutral transitive clauses commonly order subject before object before verb.'),
    ('word_order', 'vso', 'Verb-subject-object', 'Neutral transitive clauses commonly order verb before subject before object.'),
    ('word_order', 'vos', 'Verb-object-subject', 'Neutral transitive clauses commonly order verb before object before subject.'),
    ('word_order', 'ovs', 'Object-verb-subject', 'Neutral transitive clauses commonly order object before verb before subject.'),
    ('word_order', 'osv', 'Object-subject-verb', 'Neutral transitive clauses commonly order object before subject before verb.'),
    ('word_order', 'no_dominant', 'No dominant word order', 'No single basic order adequately characterizes neutral transitive clauses.'),
    ('word_order_flexibility', 'restricted', 'Restricted word order', 'Constituent ordering is relatively constrained in ordinary clauses.'),
    ('word_order_flexibility', 'flexible', 'Flexible word order', 'Several constituent orders are available, often depending on information structure.'),
    ('word_stress', 'fixed', 'Usually fixed stress', 'Stress generally occupies a predictable position; exceptions need notes.'),
    ('word_stress', 'variable', 'Variable stress', 'Stress position varies between words.'),
    ('word_stress', 'not_applicable', 'No word stress system', 'The language is not described using a word-stress system within this feature definition.');

INSERT INTO language_feature_assignment
(
    language_id,
    feature_id,
    value_code,
    notes,
    example
)
VALUES
    ('pt-BR', 'definite_articles', 'present', 'Portuguese has definite articles; regional usage and contraction patterns require separate guidance.', 'o livro; a casa'),
    ('en-US', 'definite_articles', 'present', 'Standard written English uses the definite article the. Local usage may differ.', 'the book'),
    ('en-US', 'indefinite_articles', 'present', 'Standard written English uses a/an with singular countable nouns.', 'a book; an apple'),
    ('en-US', 'noun_gender', 'absent', 'No productive grammatical gender agreement on common nouns or adjectives. Gendered pronouns and lexical pairs remain possible.', 'a good book; a good chair'),
    ('en-GB', 'definite_articles', 'present', 'Standard written English uses the definite article the. Local usage may differ.', 'the book'),
    ('en-GB', 'indefinite_articles', 'present', 'Standard written English uses a/an with singular countable nouns.', 'a book; an apple'),
    ('en-GB', 'noun_gender', 'absent', 'No productive grammatical gender agreement on common nouns or adjectives. Gendered pronouns and lexical pairs remain possible.', 'a good book; a good chair'),
    ('pt-PT', 'definite_articles', 'present', 'Portuguese has definite articles; regional usage and contraction patterns require separate guidance.', 'o livro; a casa'),
    ('en-AU', 'definite_articles', 'present', 'Standard written English uses the definite article the. Local usage may differ.', 'the book'),
    ('en-AU', 'indefinite_articles', 'present', 'Standard written English uses a/an with singular countable nouns.', 'a book; an apple'),
    ('en-AU', 'noun_gender', 'absent', 'No productive grammatical gender agreement on common nouns or adjectives. Gendered pronouns and lexical pairs remain possible.', 'a good book; a good chair'),
    ('en-CA', 'definite_articles', 'present', 'Standard written English uses the definite article the. Local usage may differ.', 'the book'),
    ('en-CA', 'indefinite_articles', 'present', 'Standard written English uses a/an with singular countable nouns.', 'a book; an apple'),
    ('en-CA', 'noun_gender', 'absent', 'No productive grammatical gender agreement on common nouns or adjectives. Gendered pronouns and lexical pairs remain possible.', 'a good book; a good chair'),
    ('en-NZ', 'definite_articles', 'present', 'Standard written English uses the definite article the. Local usage may differ.', 'the book'),
    ('en-NZ', 'indefinite_articles', 'present', 'Standard written English uses a/an with singular countable nouns.', 'a book; an apple'),
    ('en-NZ', 'noun_gender', 'absent', 'No productive grammatical gender agreement on common nouns or adjectives. Gendered pronouns and lexical pairs remain possible.', 'a good book; a good chair'),
    ('en-IE', 'definite_articles', 'present', 'Standard written English uses the definite article the. Local usage may differ.', 'the book'),
    ('en-IE', 'indefinite_articles', 'present', 'Standard written English uses a/an with singular countable nouns.', 'a book; an apple'),
    ('en-IE', 'noun_gender', 'absent', 'No productive grammatical gender agreement on common nouns or adjectives. Gendered pronouns and lexical pairs remain possible.', 'a good book; a good chair'),
    ('en-ZA', 'definite_articles', 'present', 'Standard written English uses the definite article the. Local usage may differ.', 'the book'),
    ('en-ZA', 'indefinite_articles', 'present', 'Standard written English uses a/an with singular countable nouns.', 'a book; an apple'),
    ('en-ZA', 'noun_gender', 'absent', 'No productive grammatical gender agreement on common nouns or adjectives. Gendered pronouns and lexical pairs remain possible.', 'a good book; a good chair'),
    ('en-IN', 'definite_articles', 'present', 'Standard written English uses the definite article the. Local usage may differ.', 'the book'),
    ('en-IN', 'indefinite_articles', 'present', 'Standard written English uses a/an with singular countable nouns.', 'a book; an apple'),
    ('en-IN', 'noun_gender', 'absent', 'No productive grammatical gender agreement on common nouns or adjectives. Gendered pronouns and lexical pairs remain possible.', 'a good book; a good chair'),
    ('en-SG', 'definite_articles', 'present', 'Standard written English uses the definite article the. Local usage may differ.', 'the book'),
    ('en-SG', 'indefinite_articles', 'present', 'Standard written English uses a/an with singular countable nouns.', 'a book; an apple'),
    ('en-SG', 'noun_gender', 'absent', 'No productive grammatical gender agreement on common nouns or adjectives. Gendered pronouns and lexical pairs remain possible.', 'a good book; a good chair'),
    ('en-PH', 'definite_articles', 'present', 'Standard written English uses the definite article the. Local usage may differ.', 'the book'),
    ('en-PH', 'indefinite_articles', 'present', 'Standard written English uses a/an with singular countable nouns.', 'a book; an apple'),
    ('en-PH', 'noun_gender', 'absent', 'No productive grammatical gender agreement on common nouns or adjectives. Gendered pronouns and lexical pairs remain possible.', 'a good book; a good chair'),
    ('en-NG', 'definite_articles', 'present', 'Standard written English uses the definite article the. Local usage may differ.', 'the book'),
    ('en-NG', 'indefinite_articles', 'present', 'Standard written English uses a/an with singular countable nouns.', 'a book; an apple'),
    ('en-NG', 'noun_gender', 'absent', 'No productive grammatical gender agreement on common nouns or adjectives. Gendered pronouns and lexical pairs remain possible.', 'a good book; a good chair'),
    ('en-KE', 'definite_articles', 'present', 'Standard written English uses the definite article the. Local usage may differ.', 'the book'),
    ('en-KE', 'indefinite_articles', 'present', 'Standard written English uses a/an with singular countable nouns.', 'a book; an apple'),
    ('en-KE', 'noun_gender', 'absent', 'No productive grammatical gender agreement on common nouns or adjectives. Gendered pronouns and lexical pairs remain possible.', 'a good book; a good chair'),
    ('en-JM', 'definite_articles', 'present', 'Standard written English uses the definite article the. Local usage may differ.', 'the book'),
    ('en-JM', 'indefinite_articles', 'present', 'Standard written English uses a/an with singular countable nouns.', 'a book; an apple'),
    ('en-JM', 'noun_gender', 'absent', 'No productive grammatical gender agreement on common nouns or adjectives. Gendered pronouns and lexical pairs remain possible.', 'a good book; a good chair'),
    ('en-TT', 'definite_articles', 'present', 'Standard written English uses the definite article the. Local usage may differ.', 'the book'),
    ('en-TT', 'indefinite_articles', 'present', 'Standard written English uses a/an with singular countable nouns.', 'a book; an apple'),
    ('en-TT', 'noun_gender', 'absent', 'No productive grammatical gender agreement on common nouns or adjectives. Gendered pronouns and lexical pairs remain possible.', 'a good book; a good chair'),
    ('pt-AO', 'definite_articles', 'present', 'Portuguese has definite articles; regional usage and contraction patterns require separate guidance.', 'o livro; a casa'),
    ('pt-MZ', 'definite_articles', 'present', 'Portuguese has definite articles; regional usage and contraction patterns require separate guidance.', 'o livro; a casa'),
    ('pt-CV', 'definite_articles', 'present', 'Portuguese has definite articles; regional usage and contraction patterns require separate guidance.', 'o livro; a casa'),
    ('pt-GW', 'definite_articles', 'present', 'Portuguese has definite articles; regional usage and contraction patterns require separate guidance.', 'o livro; a casa'),
    ('pt-ST', 'definite_articles', 'present', 'Portuguese has definite articles; regional usage and contraction patterns require separate guidance.', 'o livro; a casa'),
    ('pl-PL', 'definite_articles', 'absent', 'Standard Polish has no grammatical definite article; definiteness is conveyed through context and other constructions.', 'książka'),
    ('pl-PL', 'indefinite_articles', 'absent', 'Standard Polish has no grammatical indefinite article; words meaning one or some have their own uses.', 'książka'),
    ('pl-PL', 'noun_gender', 'three', 'Three principal singular genders: masculine, feminine and neuter. Masculine personal/animate/inanimate and plural agreement distinctions require additional instruction.', 'ten dom; ta książka; to dziecko');
