INSERT INTO exercise_category (name, description) VALUES
    ('vocabulary', 'Word meaning, recognition, recall, and appropriate usage.'),
    ('grammar', 'General grammatical structures and correct sentence construction.'),
    ('conjugation', 'Verb forms according to tense, mood, person, and number.'),
    ('tense', 'Understanding and correctly using grammatical tense.'),
    ('word_order', 'Correct ordering of words and phrases within sentences.'),
    ('articles', 'Correct selection and usage of definite, indefinite, and other articles.'),
    ('prepositions', 'Correct selection and usage of prepositions.'),
    ('pronouns', 'Correct selection and usage of personal, possessive, reflexive, and other pronouns.'),
    ('agreement', 'Correct gender, number, person, and other grammatical agreement.'),
    ('gender', 'Understanding and correctly applying grammatical gender.'),
    ('pluralization', 'Correct formation and usage of plural forms.'),
    ('negation', 'Correct formation and usage of negative expressions and sentences.'),
    ('questions', 'Correct formation and understanding of questions.'),
    ('conditionals', 'Understanding and constructing conditional expressions and sentences.'),
    ('comparatives', 'Correct usage of comparative and superlative forms.'),
    ('possessives', 'Correct expression of possession and possessive grammatical forms.'),
    ('idioms', 'Understanding and appropriately using idiomatic expressions.'),
    ('collocations', 'Recognizing and using words that naturally occur together.'),
    ('translation', 'Expressing equivalent meaning between the source and target languages.'),
    ('reading', 'Understanding written language in the target language.'),
    ('reading_comprehension', 'Extracting meaning, details, relationships, and implications from written text.'),
    ('listening', 'Understanding spoken language and recognizing spoken forms.'),
    ('writing', 'Producing clear, natural, and grammatically appropriate written language.'),
    ('spelling', 'Correctly spelling words according to target-language conventions.'),
    ('punctuation', 'Correct usage of punctuation according to target-language conventions.'),
    ('sentence_construction', 'Building complete, grammatical, and natural sentences from individual components.'),
    ('meaning_in_context', 'Determining the intended meaning of words and phrases from their surrounding context.'),
    ('synonyms', 'Recognizing and selecting words or expressions with similar meanings.'),
    ('antonyms', 'Recognizing and selecting words or expressions with opposite meanings.'),
    ('register', 'Choosing language appropriate to formal, informal, professional, and social contexts.');
