INSERT INTO language_exercise (language_id, definition_id)
WITH target_profiles (
    language_id, conjugate_verb, choose_article, choose_preposition,
    complete_agreement, form_plural, change_tense, transliterate, english_target
) AS (
    VALUES
        ('pt-BR', true, true, true, true, true, true, false, false),
        ('en-US', true, true, true, true, true, true, false, true),
        ('en-GB', true, true, true, true, true, true, false, true),
        ('es-ES', true, true, true, true, true, true, false, false),
        ('es-MX', true, true, true, true, true, true, false, false),
        ('fr-FR', true, true, true, true, true, true, false, false),
        ('fr-CA', true, true, true, true, true, true, false, false),
        ('de-DE', true, true, true, true, true, true, false, false),
        ('it-IT', true, true, true, true, true, true, false, false),
        ('ja-JP', true, false, false, false, false, true, true, false),
        ('ko-KR', true, false, false, false, true, true, true, false),
        ('zh-Hans-CN', false, false, true, false, false, false, true, false),
        ('pt-PT', true, true, true, true, true, true, false, false),
        ('en-AU', true, true, true, true, true, true, false, true),
        ('en-CA', true, true, true, true, true, true, false, true),
        ('es-AR', true, true, true, true, true, true, false, false),
        ('es-CO', true, true, true, true, true, true, false, false),
        ('de-AT', true, true, true, true, true, true, false, false),
        ('de-CH', true, true, true, true, true, true, false, false),
        ('nl-NL', true, true, true, true, true, true, false, false),
        ('nl-BE', true, true, true, true, true, true, false, false),
        ('sv-SE', true, true, true, true, true, true, false, false),
        ('nb-NO', true, true, true, true, true, true, false, false),
        ('nn-NO', true, true, true, true, true, true, false, false),
        ('da-DK', true, true, true, true, true, true, false, false),
        ('fi-FI', true, false, true, true, true, true, false, false),
        ('is-IS', true, true, true, true, true, true, false, false),
        ('fo-FO', true, true, true, true, true, true, false, false),
        ('pl-PL', true, false, true, true, true, true, false, false),
        ('cs-CZ', true, false, true, true, true, true, false, false),
        ('sk-SK', true, false, true, true, true, true, false, false),
        ('hu-HU', true, true, false, true, true, true, false, false),
        ('ro-RO', true, true, true, true, true, true, false, false),
        ('bg-BG', true, true, true, true, true, true, true, false),
        ('hr-HR', true, false, true, true, true, true, false, false),
        ('sr-RS', true, false, true, true, true, true, true, false),
        ('bs-BA', true, false, true, true, true, true, false, false),
        ('sl-SI', true, false, true, true, true, true, false, false),
        ('mk-MK', true, true, true, true, true, true, true, false),
        ('sq-AL', true, true, true, true, true, true, false, false),
        ('el-GR', true, true, true, true, true, true, true, false),
        ('tr-TR', true, true, false, true, true, true, false, false),
        ('ru-RU', true, false, true, true, true, true, true, false),
        ('uk-UA', true, false, true, true, true, true, true, false),
        ('be-BY', true, false, true, true, true, true, true, false),
        ('lt-LT', true, false, true, true, true, true, false, false),
        ('lv-LV', true, false, true, true, true, true, false, false),
        ('et-EE', true, false, true, true, true, true, false, false),
        ('ga-IE', true, true, true, true, true, true, false, false),
        ('gd-GB', true, true, true, true, true, true, false, false),
        ('cy-GB', true, true, true, true, true, true, false, false),
        ('mt-MT', true, true, true, true, true, true, false, false),
        ('ca-ES', true, true, true, true, true, true, false, false),
        ('eu-ES', true, true, false, true, true, true, false, false),
        ('gl-ES', true, true, true, true, true, true, false, false),
        ('oc-FR', true, true, true, true, true, true, false, false),
        ('lb-LU', true, true, true, true, true, true, false, false),
        ('hy-AM', true, true, false, true, true, true, true, false),
        ('ka-GE', true, false, false, true, true, true, true, false),
        ('az-AZ', true, false, false, true, true, true, false, false),
        ('kk-KZ', true, false, false, true, true, true, true, false),
        ('uz-UZ', true, false, false, true, true, true, true, false),
        ('ky-KG', true, false, false, true, true, true, true, false),
        ('tg-TJ', true, false, true, true, true, true, true, false),
        ('mn-MN', true, false, false, true, true, true, true, false),
        ('zh-Hant-TW', false, false, true, false, false, false, true, false),
        ('yue-Hant-HK', false, false, true, false, false, false, true, false),
        ('vi-VN', false, false, true, false, false, false, false, false),
        ('th-TH', false, false, true, false, false, false, true, false),
        ('lo-LA', false, false, true, false, false, false, true, false),
        ('km-KH', false, false, true, false, false, false, true, false),
        ('my-MM', false, false, false, false, false, false, true, false),
        ('id-ID', false, false, true, false, true, false, false, false),
        ('ms-MY', false, false, true, false, true, false, false, false),
        ('fil-PH', true, false, true, false, true, false, false, false),
        ('jv-ID', false, false, true, false, true, false, false, false),
        ('su-ID', false, false, true, false, true, false, false, false),
        ('hi-IN', true, false, false, true, true, true, true, false),
        ('ur-PK', true, false, false, true, true, true, true, false),
        ('bn-BD', true, false, false, true, true, true, true, false),
        ('pa-IN', true, false, false, true, true, true, true, false),
        ('gu-IN', true, false, false, true, true, true, true, false),
        ('mr-IN', true, false, false, true, true, true, true, false),
        ('ta-IN', true, false, false, true, true, true, true, false),
        ('te-IN', true, false, false, true, true, true, true, false),
        ('kn-IN', true, false, false, true, true, true, true, false),
        ('ml-IN', true, false, false, true, true, true, true, false),
        ('si-LK', true, false, false, true, true, true, true, false),
        ('ne-NP', true, false, false, true, true, true, true, false),
        ('fa-IR', true, true, true, true, true, true, true, false),
        ('ps-AF', true, false, true, true, true, true, true, false),
        ('he-IL', true, true, true, true, true, true, true, false),
        ('ar', true, true, true, true, true, true, true, false),
        ('ar-EG', true, true, true, true, true, true, true, false),
        ('sw', true, false, true, true, true, true, false, false),
        ('af-ZA', false, true, true, false, true, true, false, false),
        ('zu-ZA', true, false, true, true, true, true, false, false),
        ('xh-ZA', true, false, true, true, true, true, false, false),
        ('am-ET', true, true, true, true, true, true, true, false),
        ('so-SO', true, true, true, true, true, true, false, false)
),
shared_kinds (kind) AS (
    VALUES
        ('match_words'),
        ('fill_blank'),
        ('translate_sentence'),
        ('single_choice'),
        ('choose_word'),
        ('meaning_in_context'),
        ('choose_synonym'),
        ('choose_antonym'),
        ('choose_register'),
        ('choose_collocation'),
        ('choose_idiom_meaning'),
        ('reading_question'),
        ('recall_word'),
        ('complete_spelling'),
        ('choose_pronoun'),
        ('express_possession'),
        ('negate_sentence'),
        ('form_question'),
        ('make_comparison'),
        ('complete_conditional'),
        ('correct_sentence'),
        ('rewrite_register'),
        ('punctuate_sentence'),
        ('order_words'),
        ('build_sentence'),
        ('translate_to_target'),
        ('short_response'),
        ('dialogue')
),
selected_kinds AS (
    SELECT p.language_id, k.kind
    FROM target_profiles p
    CROSS JOIN shared_kinds k
    WHERE NOT (p.english_target AND k.kind IN (
        'match_words', 'translate_sentence', 'translate_to_target', 'dialogue'
    ))

    UNION ALL

    SELECT p.language_id, option.kind
    FROM target_profiles p,
    LATERAL (VALUES
        ('conjugate_verb', p.conjugate_verb),
        ('choose_article', p.choose_article),
        ('choose_preposition', p.choose_preposition),
        ('complete_agreement', p.complete_agreement),
        ('form_plural', p.form_plural),
        ('change_tense', p.change_tense),
        ('transliterate', p.transliterate)
    ) AS option(kind, enabled)
    WHERE option.enabled
)
SELECT selected.language_id,
    (SELECT id FROM exercise_definition WHERE kind = selected.kind)
FROM selected_kinds selected;
